### ISSUE TITLE
As an Inman agent I want to delete normal users on the hub (dev)

### ISSUE THREAD

**Issue by marcelaph** [marcelaph/Hub-Optimization#19]

**Comment by corellanaph** [comment]
Error when deleting admin account.
![hub_deleting_admin_account](https://cloud.githubusercontent.com/assets/24833309/21573838/06b90106-ceaf-11e6-9aaa-7268a4c9c222.PNG)

**Comment by corellanaph** [comment]
This was tested and everything is fine!
Task: https://app.asana.com/0/237284520792731/237695647788407
