### ISSUE TITLE
As an Inman agent I want to create a normal user on the hub (dev)

### ISSUE THREAD

**Issue by marcelaph** [marcelaph/Hub-Optimization#22]

**Comment by corellanaph** [comment]
1. Login failed with users created on hub.
2. Stripe doesn’t show users created on hub.
3. Coupon doesn’t work, the discount is not applied.  https://youtu.be/szNe9apBCO4




![customer login failed](https://cloud.githubusercontent.com/assets/24833309/21571887/480a2bd2-ce99-11e6-92f7-67aa64c1e511.png)

![users are not on stripe](https://cloud.githubusercontent.com/assets/24833309/21571894/55508ef8-ce99-11e6-95c2-aef70369592b.png)

**Comment by corellanaph** [comment]
3. This was tested and everything is fine! Task: https://app.asana.com/0/237284520792731/237749577931469
