### ISSUE TITLE
As an Inman agent I want to create Admin users on the hub (dev)

### ISSUE THREAD

**Issue by marcelaph** [marcelaph/Hub-Optimization#23]

**Comment by corellanaph** [comment]
Phone field:
1. Accepts any character.
2. Add max length and/or specify the which the error is.

![phone field](https://cloud.githubusercontent.com/assets/24833309/21568920/f57943c8-ce7d-11e6-8df9-3e4a71c3759d.png)
![phone max lenght error](https://cloud.githubusercontent.com/assets/24833309/21568922/f72b310e-ce7d-11e6-9751-f6a19a3b04d7.png)
![phone max lenght error](https://cloud.githubusercontent.com/assets/24833309/21568924/f9c4f6ac-ce7d-11e6-9e2a-1fdf3412ca43.png)

**Comment by corellanaph** [comment]
Point 1 ("Accepts any character.") is hold on, because they rarely pull this data in from anywhere.

**Comment by corellanaph** [comment]
2. This was tested and everything is fine! Task: https://app.asana.com/0/237284520792731/237312515276359
